---
- name: "Ensure Dependencies are present. (Ansible Interpreter Python 2)"
  ansible.builtin.package:
    name: yum-utils
    state: present
  when: not ansible_python.executable = "/usr/bin/python3"

- name: "Ensure Dependencies are present. (Ansible Interpreter Python 3)"
  ansible.builtin.dnf:
    name: yum-utils
    state: present
  when: ansible_python.executable = "/usr/bin/python3"

- name: "Mark packages on hold."
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: 'exclude={{ item }}'
    state: present
  with_items: "{{ upgrade_packages_on_hold }}"

- name: "Store List of Updates for further Inspection."
  ansible.builtin.command: yum check-update
  args:
  register: upgrade_update_list_yum
  failed_when: upgrade_update_list_yum.rc > 100
  ignore_errors: true
  when: upgrade_reporting_enable | bool

- name: "Upgrade via YUM."
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true

- name: "Cleanup via YUM."
  ansible.builtin.yum:
    state: absent
    autoremove: true

- name: "Unhold Packages."
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: 'exclude={{ item }}'
    state: absent
  with_items: "{{ upgrade_packages_on_hold }}"

- name: "Check for Reboot Hint."
  ansible.builtin.shell: needs-restarting -r
  register: reboot_hint_yum
  failed_when: reboot_hint_yum.rc >= 2
  changed_when: reboot_hint_yum.rc == 1

- name: "Check for Service Restarts."
  ansible.builtin.shell: needs-restarting -s
  register: service_restarts_yum
  changed_when: "service_restarts_yum.stdout | length"

- name: "Set Reboot Hint."
  ansible.builtin.set_fact:
    reboot_hint: true
  when: reboot_hint_yum.rc == 1

- name: "Set Service Restarts."
  ansible.builtin.set_fact:
    service_restarts: "{{ service_restarts_yum.stdout_lines }}"
  when: "service_restarts_yum.stdout_lines | length"
